export const THEMES = [
  {
    name: "Tokyo Night Dark",
    triads: [
      {
        main: "#1a1b26",
        variant: "#3d4060",
        fg: "#c0caf5",
        usage: "background",
      },
      {
        main: "#414868",
        variant: "#7a85b5",
        fg: "#c0caf5",
        usage: "dark blue (surface / muted)",
      },
      {
        main: "#565f89",
        variant: "#9aa5d0",
        fg: "#c0caf5",
        usage: "dark blue (overlay)",
      },
      {
        main: "#9aa5ce",
        variant: "#5660a0",
        fg: "#1a1b26",
        usage: "muted blue",
      },
      {
        main: "#a9b1d6",
        variant: "#6a72a8",
        fg: "#1a1b26",
        usage: "muted blue (lighter)",
      },
      {
        main: "#c0caf5",
        variant: "#7a86c5",
        fg: "#1a1b26",
        usage: "lavender (default foreground)",
      },
      { main: "#bb9af7", variant: "#6a3fc4", fg: "#1a1b26", usage: "purple" },
      { main: "#7aa2f7", variant: "#2d5cc4", fg: "#1a1b26", usage: "blue" },
      {
        main: "#7dcfff",
        variant: "#2d8fc4",
        fg: "#1a1b26",
        usage: "light blue",
      },
      {
        main: "#2ac3de",
        variant: "#1a7a8c",
        fg: "#1a1b26",
        usage: "blue (cyan-ish)",
      },
      { main: "#b4f9f8", variant: "#5fbab9", fg: "#1a1b26", usage: "cyan" },
      { main: "#73dacb", variant: "#2d9a8a", fg: "#1a1b26", usage: "teal" },
      { main: "#9ece6a", variant: "#5e8e2d", fg: "#1a1b26", usage: "green" },
      { main: "#cfc9c2", variant: "#8a857e", fg: "#1a1b26", usage: "beige" },
      { main: "#e0af68", variant: "#9a6e2d", fg: "#1a1b26", usage: "yellow" },
      { main: "#ff9e64", variant: "#c45c20", fg: "#1a1b26", usage: "orange" },
      {
        main: "#f7768e",
        variant: "#b03a4f",
        fg: "#1a1b26",
        usage: "red / pink",
      },
    ],
  },
  {
    name: "Tokyo Night Storm",
    triads: [
      {
        main: "#24283b",
        variant: "#4a5170",
        fg: "#c0caf5",
        usage: "background",
      },
      {
        main: "#565f89",
        variant: "#9aa5d0",
        fg: "#c0caf5",
        usage: "dark blue (surface / overlay)",
      },
      {
        main: "#9aa5ce",
        variant: "#5660a0",
        fg: "#1a1b26",
        usage: "muted blue",
      },
      {
        main: "#a9b1d6",
        variant: "#6a72a8",
        fg: "#1a1b26",
        usage: "muted blue (lighter)",
      },
      {
        main: "#c0caf5",
        variant: "#7a86c5",
        fg: "#1a1b26",
        usage: "lavender (default foreground)",
      },
      { main: "#bb9af7", variant: "#6a3fc4", fg: "#1a1b26", usage: "purple" },
      { main: "#7aa2f7", variant: "#2d5cc4", fg: "#1a1b26", usage: "blue" },
      {
        main: "#7dcfff",
        variant: "#2d8fc4",
        fg: "#1a1b26",
        usage: "light blue",
      },
      {
        main: "#2ac3de",
        variant: "#1a7a8c",
        fg: "#1a1b26",
        usage: "blue (cyan-ish)",
      },
      { main: "#b4f9f8", variant: "#5fbab9", fg: "#1a1b26", usage: "cyan" },
      { main: "#73dacb", variant: "#2d9a8a", fg: "#1a1b26", usage: "teal" },
      { main: "#9ece6a", variant: "#5e8e2d", fg: "#1a1b26", usage: "green" },
      { main: "#cfc9c2", variant: "#8a857e", fg: "#1a1b26", usage: "beige" },
      { main: "#e0af68", variant: "#9a6e2d", fg: "#1a1b26", usage: "yellow" },
      { main: "#ff9e64", variant: "#c45c20", fg: "#1a1b26", usage: "orange" },
      {
        main: "#f7768e",
        variant: "#b03a4f",
        fg: "#1a1b26",
        usage: "red / pink",
      },
    ],
  },
  {
    name: "Tokyo Night Light",
    triads: [
      {
        main: "#e6e7ed",
        variant: "#a7a9b3",
        fg: "#343b58",
        usage: "background",
      },
      {
        main: "#6c6e75",
        variant: "#a8aab1",
        fg: "#e6e7ed",
        usage: "gray (muted text)",
      },
      {
        main: "#40434f",
        variant: "#80848f",
        fg: "#e6e7ed",
        usage: "dark (overlay)",
      },
      {
        main: "#343b58",
        variant: "#6a749c",
        fg: "#e6e7ed",
        usage: "dark blue (default foreground)",
      },
      { main: "#5a3e8e", variant: "#9479c0", fg: "#e6e7ed", usage: "purple" },
      { main: "#2959aa", variant: "#5e8fdc", fg: "#e6e7ed", usage: "blue" },
      {
        main: "#0f4b6e",
        variant: "#4283ad",
        fg: "#e6e7ed",
        usage: "blue (deep)",
      },
      {
        main: "#006c86",
        variant: "#3aa3bc",
        fg: "#e6e7ed",
        usage: "blue (cyan-ish)",
      },
      { main: "#33635c", variant: "#6da39a", fg: "#e6e7ed", usage: "teal" },
      { main: "#385f0d", variant: "#6e9a40", fg: "#e6e7ed", usage: "green" },
      { main: "#634f30", variant: "#9d8662", fg: "#e6e7ed", usage: "beige" },
      { main: "#8f5e15", variant: "#c89348", fg: "#e6e7ed", usage: "yellow" },
      { main: "#965027", variant: "#c98456", fg: "#e6e7ed", usage: "orange" },
      {
        main: "#8c4351",
        variant: "#c47785",
        fg: "#e6e7ed",
        usage: "red / pink",
      },
    ],
  },
  {
    name: "Monokai Pro",
    triads: [
      {
        main: "#272822",
        variant: "#4a4b40",
        fg: "#F8F8F2",
        usage: "background",
      },
      {
        main: "#49483E",
        variant: "#7a7866",
        fg: "#F8F8F2",
        usage: "selection / lineHighlight / invisibles",
      },
      { main: "#75715E", variant: "#a8a48d", fg: "#F8F8F2", usage: "comment" },
      { main: "#F8F8F0", variant: "#b0b09a", fg: "#272822", usage: "caret" },
      {
        main: "#F8F8F2",
        variant: "#b0b0a8",
        fg: "#272822",
        usage: "foreground",
      },
      {
        main: "#F92672",
        variant: "#b00a4d",
        fg: "#F8F8F2",
        usage: "keyword / storage / tag name / invalid bg",
      },
      {
        main: "#FD971F",
        variant: "#b56610",
        fg: "#272822",
        usage: "function argument (parameter)",
      },
      { main: "#E6DB74", variant: "#a89d3f", fg: "#272822", usage: "string" },
      {
        main: "#A6E22E",
        variant: "#6e9e15",
        fg: "#272822",
        usage: "class / function name / inherited / tag attribute",
      },
      {
        main: "#66D9EF",
        variant: "#2596b0",
        fg: "#272822",
        usage: "storage type / library function / constant / class",
      },
      {
        main: "#AE81FF",
        variant: "#6e3fc8",
        fg: "#272822",
        usage: "number / built-in / user constant / invalid deprecated bg",
      },
    ],
  },
];
